name: HitEffect
version: 1.0.0
api: 5.0.0
main: VsrStudio\HitEffect\Main
author: VsrStudio
description: HitEffect CubeOcean Mysql Support

softdepend:
  - CoinAPI
  - libasynql
  - FormAPI

commands:
  hiteffect:
    description: Buka menu
    usage: /hiteffect
    permission: hiteffect.command

permissions:
  hiteffect.command:
    default: true
  hiteffect.heart:
    default: op
  hiteffect.ink:
    default: op
  hiteffect.flame:
    default: op
  hiteffect.lava:
    default: op
  hiteffect.water:
    default: op
  hiteffect.smoke:
    default: op
