database:
  type: mysql
  mysql:
    host: 127.0.0.1
    username: root
    password: "password"
    schema: hit_effect
    port: 3306
  worker-limit: 2

effects:
  heart:
    price: 30000
    button: "Love Heart"
    permission: hiteffect.heart

  ink:
    price: 30000
    button: "Ink Splash"
    permission: hiteffect.ink

  flame:
    price: 30000
    button: "Fire Trail"
    permission: hiteffect.flame

  lava:
    price: 30000
    button: "Lava Spark"
    permission: hiteffect.lava

  water:
    price: 30000
    button: "Water Drop"
    permission: hiteffect.water

  smoke:
    price: 30000
    button: "Smoke Burst"
    permission: hiteffect.smoke
